CREATE CLUSTERED INDEX IX_Faixa_Album
ON Faixa (album)
ON FG_DADOS_GERAIS
WITH (FILLFACTOR = 100);
GO


CREATE NONCLUSTERED INDEX IX_Faixa_Tipo_Composicao
ON Faixa (tipo_comp)
ON FG_DADOS_GERAIS
WITH (FILLFACTOR = 100);
GO