USE BDSpotPer
GO

CREATE NONCLUSTERED INDEX IX_Faixa_Album
ON Faixa (album)
WITH (FILLFACTOR = 100)
ON FG_PLAYLISTS;
GO


CREATE NONCLUSTERED INDEX IX_Faixa_Tipo_Composicao
ON Faixa (tipo_comp)
WITH (FILLFACTOR = 100)
ON FG_PLAYLISTS;
GO